services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    restart: always
    networks:
      - default
    environment:
      - DATABASE_URL=psql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - default
    environment:
      - DOMAIN
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template:ro
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: bot
    restart: always
    networks:
      - default
    environment:
      - DATABASE_URL=psql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - BOT_TOKEN
      - ADMIN_CHAT_ID
      - ADMIN_USERNAME
  postgres:
    image: postgres
    restart: always
    networks:
      - default
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - db-data:/var/lib/postgresql/data
networks:
  default:
volumes:
  db-data:
